import {useEffect, useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import ReactECharts from 'echarts-for-react';

const api=async(path:string)=>{const response=await fetch(`/api/v1${path}`);if(!response.ok)throw new Error(`HTTP ${response.status}`);return response.json()};
const money=(value:any)=>value==null?'—':Math.abs(Number(value))>=1e8?`${(Number(value)/1e8).toFixed(2)}亿`:`${(Number(value)/1e4).toFixed(0)}万`;
const percent=(value:any)=>value==null?'—':`${Number(value).toFixed(2)}%`;

export default function LongHu(){
  const [date,setDate]=useState('');
  const [selected,setSelected]=useState<any>(null);
  const dates=useQuery({queryKey:['lhb-dates'],queryFn:()=>api('/lhb/dates')});
  useEffect(()=>{const latest=dates.data?.data?.[0]?.trade_date;if(latest&&!date)setDate(String(latest))},[dates.data,date]);
  const records=useQuery({queryKey:['lhb',date],queryFn:()=>api(`/lhb/records?trade_date=${date}&limit=500`),enabled:!!date});
  const rows=records.data?.data||[];
  useEffect(()=>{if(rows.length&&!rows.some((row:any)=>row.symbol===selected?.symbol))setSelected(rows[0]);if(!rows.length)setSelected(null)},[records.data,selected?.symbol,rows]);
  const seats=useQuery({queryKey:['lhb-seats',date,selected?.symbol],queryFn:()=>api(`/lhb/seats?trade_date=${date}&symbol=${selected.symbol}&limit=500`),enabled:!!selected&&!!date});
  const detail=useQuery({queryKey:['lhb-detail',date,selected?.symbol],queryFn:()=>api(`/lhb/detail/${selected.symbol}?trade_date=${date}&days=30`),enabled:!!selected&&!!date});
  const seatRows=seats.data?.data||[];
  const coverage=seats.data?.coverage;
  const bars=detail.data?.data?.bars||[];
  const moneyflow=detail.data?.data?.moneyflow||[];
  const hotMoney=detail.data?.data?.hot_money||[];
  const historyRows=detail.data?.data?.history||[];
  const net=rows.reduce((sum:number,row:any)=>sum+Number(row.net_amount||0),0);
  const klineOption={backgroundColor:'#0d141b',animation:false,textStyle:{color:'#788797'},grid:{left:56,right:20,top:24,bottom:48},tooltip:{trigger:'axis',axisPointer:{type:'cross'},backgroundColor:'#111b24',borderColor:'#2a3945',textStyle:{color:'#dce5ee'}},xAxis:{type:'category',data:bars.map((row:any)=>row.trade_date),axisLabel:{color:'#788797'},axisLine:{lineStyle:{color:'#26333e'}}},yAxis:{scale:true,axisLabel:{color:'#788797'},splitLine:{lineStyle:{color:'#1b2730'}}},dataZoom:[{type:'inside'},{type:'slider',height:16,bottom:7,borderColor:'#26333e',backgroundColor:'#0a1016',fillerColor:'#214b3e'}],series:[{type:'candlestick',data:bars.map((row:any)=>[row.open,row.close,row.low,row.high]),itemStyle:{color:'#ff6577',color0:'#3dd6a2',borderColor:'#ff6577',borderColor0:'#3dd6a2'}}]};
  return <>
    <div className="page-title"><div><span className="eyebrow">DRAGON & TIGER LIST</span><h1>龙虎榜</h1><p className="muted">每日统计、机构/营业部席位、游资标注与个股资金流交叉研究</p></div><select value={date} onChange={event=>{setDate(event.target.value);setSelected(null)}}>{(dates.data?.data||[]).map((item:any)=><option value={item.trade_date} key={item.trade_date}>{item.trade_date}</option>)}</select></div>
    <div className="cards"><div className="card"><span>上榜记录</span><strong>{rows.length}</strong></div><div className="card"><span>涉及股票</span><strong>{new Set(rows.map((row:any)=>row.symbol)).size}</strong></div><div className="card"><span>榜单合计净额</span><strong>{money(net)}</strong></div><div className="card"><span>当前选股</span><strong>{selected?.name||'—'}</strong></div></div>
    <div className="lhb-master-detail"><section className="panel lhb-records"><div className="panel-head"><div><span className="section-kicker">DAILY LIST</span><h2>当日榜单</h2></div><span className="chip">top_list</span></div><div className="table-wrap"><table><thead><tr><th>股票</th><th>涨跌幅</th><th>换手率</th><th>成交额</th><th>买入额</th><th>卖出额</th><th>净额</th><th>席位</th><th>上榜原因</th></tr></thead><tbody>{rows.map((row:any)=><tr className={selected?.symbol===row.symbol?'selected':''} onClick={()=>setSelected(row)} key={`${row.symbol}-${row.reason}`}><td><b>{row.name}</b><small>{row.symbol}</small></td><td className={Number(row.pct_change)>=0?'rise':'fall'}>{percent(row.pct_change)}</td><td>{percent(row.turnover_rate)}</td><td>{money(row.amount)}</td><td>{money(row.l_buy)}</td><td>{money(row.l_sell)}</td><td className={Number(row.net_amount)>=0?'rise':'fall'}>{money(row.net_amount)}</td><td><b>{row.seat_count}</b><small>机构 {row.institution_count} / 营业部 {row.business_seat_count}</small></td><td className="reason-cell">{row.reason}</td></tr>)}</tbody></table>{!rows.length&&<div className="empty">所选日期暂无龙虎榜记录</div>}</div></section><section className="panel chart-panel"><div className="panel-head"><div><span className="section-kicker">STOCK CONTEXT · 30 DAYS</span><h2>{selected?`${selected.name} K 线`:'选择一只股票'}</h2></div><span className={`coverage ${coverage?.status||'missing'}`}>{coverage?.description||'等待席位数据'}</span></div>{bars.length?<ReactECharts style={{height:390}} option={klineOption}/>:<div className="empty-state">点击左侧股票查看近 30 个交易日</div>}<div className="stock-summary"><span>榜单净额 {money(selected?.net_amount)}</span><span>成交占比 {percent(selected?.amount_rate)}</span><span>最新主力净流入 {money(moneyflow[0]?.net_amount)}</span><span>主力净流入占比 {percent(moneyflow[0]?.net_amount_rate)}</span></div></section></div>
    <div className="lhb-secondary-grid"><section className="panel table-panel lhb-seats"><div className="panel-head"><div><span className="section-kicker">SEAT DISCLOSURE</span><h2>机构 / 营业部席位明细</h2></div><span className="chip">top_inst · {seatRows.length} 条</span></div><div className="table-wrap"><table><thead><tr><th>类型</th><th>方向</th><th>席位</th><th>买入</th><th>买入占比</th><th>卖出</th><th>卖出占比</th><th>净买入</th><th>上榜原因</th></tr></thead><tbody>{seatRows.map((row:any,index:number)=><tr key={`${row.seat_name}-${row.side}-${row.reason}-${index}`}><td><span className={`seat-type ${row.seat_type==='机构'?'institution':''}`}>{row.seat_type}</span></td><td>{row.side_label}</td><td>{row.seat_name}</td><td>{money(row.buy)}</td><td>{percent(row.buy_rate)}</td><td>{money(row.sell)}</td><td>{percent(row.sell_rate)}</td><td className={Number(row.net_buy)>=0?'rise':'fall'}>{money(row.net_buy)}</td><td className="reason-cell">{row.reason}</td></tr>)}</tbody></table>{selected&&!seatRows.length&&<div className="empty">上游未返回该股票的席位明细</div>}</div></section><section className="panel table-panel"><div className="panel-head"><div><span className="section-kicker">HOT MONEY</span><h2>游资识别</h2></div><span className="chip">hm_list / hm_detail</span></div><div className="table-wrap"><table><thead><tr><th>日期</th><th>游资</th><th>关联席位</th><th>买入</th><th>卖出</th><th>净额</th><th>标签</th></tr></thead><tbody>{hotMoney.map((row:any,index:number)=><tr key={`${row.trade_date}-${row.hot_money_name}-${index}`}><td>{row.trade_date}</td><td><b>{row.hot_money_name}</b><small>{row.description||'—'}</small></td><td>{row.associated_orgs||'—'}</td><td>{money(row.buy_amount)}</td><td>{money(row.sell_amount)}</td><td className={Number(row.net_amount)>=0?'rise':'fall'}>{money(row.net_amount)}</td><td>{row.tag||'—'}</td></tr>)}</tbody></table>{selected&&!hotMoney.length&&<div className="empty">近期待选日期前暂无已识别游资记录</div>}</div></section><section className="panel table-panel"><div className="panel-head"><div><span className="section-kicker">LIST HISTORY</span><h2>历史上榜</h2></div><span className="chip">最近 50 条</span></div><div className="table-wrap"><table><thead><tr><th>日期</th><th>涨跌幅</th><th>换手率</th><th>净额</th><th>成交占比</th><th>原因</th></tr></thead><tbody>{historyRows.map((row:any,index:number)=><tr key={`${row.trade_date}-${row.reason}-${index}`}><td>{row.trade_date}</td><td className={Number(row.pct_change)>=0?'rise':'fall'}>{percent(row.pct_change)}</td><td>{percent(row.turnover_rate)}</td><td className={Number(row.net_amount)>=0?'rise':'fall'}>{money(row.net_amount)}</td><td>{percent(row.amount_rate)}</td><td className="reason-cell">{row.reason}</td></tr>)}</tbody></table></div></section></div>
  </>;
}
