import {useEffect, useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import ReactECharts from 'echarts-for-react';
import './popularity.css';

const api=async(path:string)=>{const response=await fetch(`/api/v1${path}`);if(!response.ok)throw new Error(`HTTP ${response.status}`);return response.json()};
const pct=(value:any)=>value==null?'—':`${Number(value)>0?'+':''}${Number(value).toFixed(2)}%`;

export default function Popularity(){
  const [source,setSource]=useState<'dc_hot'|'ths_hot'>('dc_hot');
  const [date,setDate]=useState('');
  const [selected,setSelected]=useState<any>(null);
  const sourceLabel=source==='dc_hot'?'东方财富':'同花顺';
  const dates=useQuery({queryKey:['popularity-dates',source],queryFn:()=>api(`/popularity/dates?source=${source}`)});
  useEffect(()=>{const latest=dates.data?.data?.[0]?.trade_date;if(latest&&!date)setDate(String(latest))},[dates.data,date]);
  const ranking=useQuery({queryKey:['rank',source,date],queryFn:()=>api(`/popularity/rankings?source=${source}&trade_date=${date}&limit=100`),enabled:!!date});
  const rows=ranking.data?.data||[];
  useEffect(()=>{if(rows.length&&!rows.some((row:any)=>row.symbol===selected?.symbol))setSelected(rows[0]);if(!rows.length)setSelected(null)},[ranking.data,selected?.symbol,rows]);
  const detail=useQuery({queryKey:['popularity-detail',source,date,selected?.symbol],queryFn:()=>api(`/popularity/detail/${selected.symbol}?source=${source}&end_date=${date}&days=30`),enabled:!!selected&&!!date});
  const bars=detail.data?.data?.bars||[];
  const ranks=detail.data?.data?.ranks||[];
  const changeSource=(next:'dc_hot'|'ths_hot')=>{setSource(next);setDate('');setSelected(null)};
  const klineOption={backgroundColor:'#0d141b',animation:false,textStyle:{color:'#788797'},grid:{left:56,right:20,top:24,bottom:48},tooltip:{trigger:'axis',axisPointer:{type:'cross'},backgroundColor:'#111b24',borderColor:'#2a3945',textStyle:{color:'#dce5ee'}},xAxis:{type:'category',data:bars.map((row:any)=>row.trade_date),axisLabel:{color:'#788797'},axisLine:{lineStyle:{color:'#26333e'}}},yAxis:{scale:true,axisLabel:{color:'#788797'},splitLine:{lineStyle:{color:'#1b2730'}}},dataZoom:[{type:'inside'},{type:'slider',height:16,bottom:7,borderColor:'#26333e',backgroundColor:'#0a1016',fillerColor:'#214b3e'}],series:[{name:'日K',type:'candlestick',data:bars.map((row:any)=>[row.open,row.close,row.low,row.high]),itemStyle:{color:'#ff6577',color0:'#3dd6a2',borderColor:'#ff6577',borderColor0:'#3dd6a2'}}]};
  const rankOption={backgroundColor:'#0d141b',animation:false,textStyle:{color:'#788797'},grid:{left:48,right:20,top:24,bottom:48},tooltip:{trigger:'axis',backgroundColor:'#111b24',borderColor:'#2a3945',textStyle:{color:'#dce5ee'}},xAxis:{type:'category',data:ranks.map((row:any)=>row.trade_date),axisLabel:{color:'#788797'},axisLine:{lineStyle:{color:'#26333e'}}},yAxis:{type:'value',inverse:true,min:1,max:100,axisLabel:{color:'#788797'},splitLine:{lineStyle:{color:'#1b2730'}}},series:[{name:'最终排名',type:'line',smooth:.25,symbolSize:7,data:ranks.map((row:any)=>row.rank),lineStyle:{color:'#54a7ff',width:2},itemStyle:{color:'#54a7ff'},areaStyle:{color:'rgba(84,167,255,.08)'}}]};
  return <>
    <div className="page-title"><div><span className="eyebrow">POPULARITY SIGNALS</span><h1>人气研究</h1><p className="muted">东财 / 同花顺每日最终 Top100 · 收益按后续有效交易日计算，两个来源不混排</p></div><div className="popularity-controls"><div className="segmented source-switch"><button className={source==='dc_hot'?'active':''} onClick={()=>changeSource('dc_hot')}>东方财富</button><button className={source==='ths_hot'?'active':''} onClick={()=>changeSource('ths_hot')}>同花顺</button></div><select value={date} disabled={!dates.data?.data?.length} onChange={event=>{setDate(event.target.value);setSelected(null)}}><option value="" disabled>选择数据日期</option>{(dates.data?.data||[]).map((item:any)=><option value={item.trade_date} key={item.trade_date}>{item.trade_date}</option>)}</select></div></div>
    <div className="cards"><div className="card"><span>最终榜单记录</span><strong>{rows.length}</strong></div><div className="card"><span>榜单口径</span><strong>Top100</strong></div><div className="card"><span>当前选股</span><strong>{selected?.name||'—'}</strong></div><div className="card"><span>数据来源</span><strong>{rows.length?sourceLabel:'—'}</strong></div></div>
    <div className="popularity-detail-grid"><section className="panel chart-panel"><div className="panel-head"><div><span className="section-kicker">PRICE · 30 TRADING DAYS</span><h2>{selected?`${selected.name} K 线`:'点击榜单股票查看 K 线'}</h2></div><span className="chip">截至 {date||'—'}</span></div>{bars.length?<ReactECharts style={{height:340}} option={klineOption}/>:<div className="empty-state">{selected?'暂无对应日线':'请先选择股票'}</div>}</section><section className="panel chart-panel"><div className="panel-head"><div><span className="section-kicker">RANK HISTORY</span><h2>{selected?`${sourceLabel}最终人气变化`:'人气变化'}</h2></div><span className="chip">低排名更热门</span></div>{ranks.length?<ReactECharts style={{height:340}} option={rankOption}/>:<div className="empty-state">近 30 个交易日暂无其他上榜记录</div>}</section></div>
    <section className="panel table-panel popularity-table"><div className="panel-head"><div><span className="section-kicker">FINAL SNAPSHOT</span><h2>最终榜单 Top100</h2></div><div><span className="chip source-chip">{sourceLabel}</span><span className="chip">{date}</span></div></div><div className="table-wrap"><table><thead><tr><th>排名</th><th>股票</th><th>次日涨跌幅</th><th>3日涨跌幅</th><th>5日涨跌幅</th><th>排名变化</th><th>热度</th><th>上榜说明</th></tr></thead><tbody>{rows.map((row:any)=><tr className={selected?.symbol===row.symbol?'selected':''} onClick={()=>setSelected(row)} key={`${row.endpoint}-${row.symbol}`}><td><b className="rank-number">{row.rank}</b></td><td><b>{row.name}</b><small>{row.symbol} · {sourceLabel}</small></td><td className={row.next_day_return==null?'':Number(row.next_day_return)>=0?'rise':'fall'}><b>{pct(row.next_day_return)}</b><small>{row.next_trade_date||'等待后续交易日'}</small></td><td className={row.day_3_return==null?'':Number(row.day_3_return)>=0?'rise':'fall'}><b>{pct(row.day_3_return)}</b><small>{row.day_3_trade_date||'等待后续交易日'}</small></td><td className={row.day_5_return==null?'':Number(row.day_5_return)>=0?'rise':'fall'}><b>{pct(row.day_5_return)}</b><small>{row.day_5_trade_date||'等待后续交易日'}</small></td><td className={row.rank_change==null?'':Number(row.rank_change)>=0?'rise':'fall'}>{row.rank_change??'—'}</td><td>{row.heat??'—'}</td><td>{row.rank_reason||row.concept||'—'}</td></tr>)}</tbody></table>{!rows.length&&<div className="empty">所选日期暂无最终榜单</div>}</div></section>
  </>;
}
